apiVersion: apps/v1
kind: Deployment
metadata:
  name: elearning-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: elearning-backend
  template:
    metadata:
      labels:
        app: elearning-backend
    spec:
      containers:
        - name: backend
          image: elearning-backend
          ports:
            - containerPort: 5000
